- nguyen_van_giang/lesson2_format_assignment.php
- nguyen_van_giang/lesson2_simple_format_php_code_tool.php
- nguyen_van_giang/lesson2_star_no5.php
> Lesson2 - For loop - Function (Star and Formatter tool)

- NguyenThuPhuong/currency_conversion_class.php
> Chuyển đổi tiền tệ

- cao_van_thao/lesson3/cur.php
- cao_van_thao/lesson3/currency-exchange.php
- cao_van_thao/lesson3/currency.php
> lesson3_CurencyPhp

- nguyen_dinh_hieu/change_money_class.php
> lesson5 change_money_class

- Le_duong/LoadDB/connect.php
- Le_duong/LoadDB/index.php
- Le_duong/LoadDB/view.php
- Le_duong/LoadDB/viewDB.php
//Create data
//Read data from database
> Le_Duong submit 

- nguyen_dinh_hieu/connect.php
- nguyen_dinh_hieu/delete.php
- nguyen_dinh_hieu/edit.php
- nguyen_dinh_hieu/selectdata_mysql.php
- nguyen_dinh_hieu/update.php
> bai tap mysql_php

- NguyenThuPhuong/add_person.php
- NguyenThuPhuong/connect.php
- NguyenThuPhuong/delete_person.php
- NguyenThuPhuong/edit_person.php
- NguyenThuPhuong/index.php
Hiển thị dữ liệu
Thêm dữ liệu 
Xóa dữ liệu 
Sửa dữ liệu
> HW - Mysql

- tran_kien_giang/laravel_routing/inputget.blade.php
- tran_kien_giang/laravel_routing/inputpost.blade.php
- tran_kien_giang/laravel_routing/outputget.blade.php
- tran_kien_giang/laravel_routing/outputpost.blade.php
- tran_kien_giang/laravel_routing/web.php
- tran_kien_giang/laravel_routing/welcome.blade.php
> [Giang_TK] -Routing

- nguyen_van_giang/laravel-app/README.md
- nguyen_van_giang/laravel-app/app/View/Components/MyAppLayout.php
- nguyen_van_giang/laravel-app/resources/views/home-page.blade.php
- nguyen_van_giang/laravel-app/resources/views/layouts/customers/my-app.blade.php
- nguyen_van_giang/laravel-app/resources/views/layouts/customers/my-navigation.blade.php
- nguyen_van_giang/laravel-app/resources/views/my-directory/child-page.blade.php
- nguyen_van_giang/laravel-app/routes/web.php
https://github.com/VanGiang/php2104_php/tree/view-layout/nguyen_van_giang/laravel-app#how-to-run-project
https://user-images.githubusercontent.com/49383891/131205031-7723bd94-7a58-4e6e-9d57-3700b892fd6d.mov
> [GiangNV] Create basic layout

- nguyen_dinh_hieu/laravel-fw/app/Providers/AppServiceProvider.php
- nguyen_dinh_hieu/laravel-fw/app/View/Components/mylayout.php
- nguyen_dinh_hieu/laravel-fw/resources/views/components/mylayout.blade.php
- nguyen_dinh_hieu/laravel-fw/resources/views/view_demo.blade.php
- nguyen_dinh_hieu/laravel-fw/resources/views/view_mvc/my_view_mvc.blade.php
- nguyen_dinh_hieu/laravel-fw/routes/web.php
> [Hieu_ND --Blade View]

- tran_kien_giang/laravel_component/Alert.php
- tran_kien_giang/laravel_component/Header.php
- tran_kien_giang/laravel_component/about.blade.php
- tran_kien_giang/laravel_component/alert.blade.php
- tran_kien_giang/laravel_component/contact.blade.php
- tran_kien_giang/laravel_component/header.blade.php
- tran_kien_giang/laravel_component/home.blade.php
- tran_kien_giang/laravel_component/web.php
https://user-images.githubusercontent.com/83223418/131342381-8cba7e5e-66a3-40d7-ab13-521c7c08beb7.mp4
LARAVEL_Component
> [Giang-TK] - laravel_component

- nguyen_van_giang/laravel-app/README.md
- nguyen_van_giang/laravel-app/composer.json
- nguyen_van_giang/laravel-app/composer.lock
- nguyen_van_giang/laravel-app/config/database.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_03_123632_creat_products_table.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_03_142452_update_products_table.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_04_040531_create_categories_table.php
- nguyen_van_giang/laravel-app/database/seeders/CategorySeeder.php
- nguyen_van_giang/laravel-app/database/seeders/DatabaseSeeder.php
- nguyen_van_giang/laravel-app/database/seeders/ProductSeeder.php
```
*************************** 99. row ***************************
id: 99
category_id: 1
user_id: 1
name: Laney Lakin
description: Ullam assumenda magnam tempore est illum molestiae dolores. Sed hic et non neque molestiae et illo. Eum blanditiis neque quod laudantium consequuntur consequatur sapiente. Optio animi et itaque odio.
price: 782
image: https://via.placeholder.com/640x480.png/0033bb?text=aut
quantity: 169
rate: 5
sold_cnt: 73
is_public: 1
created_at: NULL
updated_at: NULL
sale_off: 44
*************************** 100. row ***************************
id: 100
category_id: 1
user_id: 1
name: Miss Aileen Franecki V
description: Molestias ut quae quia. Nostrum iusto aut natus esse rerum accusantium nobis sit. Laborum fuga ut quam quibusdam harum.
price: 227
image: …
```
> Create migration file

- Le_duong/Laravel/eCommerce/database/migrations/2021_09_05_152200_create_categories_table.php
- Le_duong/Laravel/eCommerce/database/migrations/2021_09_05_155139_create_products_table.php
- Le_duong/Laravel/eCommerce/database/migrations/2021_09_05_155357_update_products_table.php
- Le_duong/Laravel/eCommerce/database/migrations/2021_09_05_155624_create_brands_table.php
- Le_duong/Laravel/eCommerce/database/seeders/DatabaseSeeder.php
- Le_duong/Laravel/eCommerce/database/seeders/ProductsSeeder.php
//migrate && generates fake data
> [Leduong]:migrate && generates fake data

- dinh_ngoc_do/laravel-app/database/migrations/2021_09_03_125323_create_persons_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_03_130458_create_products_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_03_132751_update_products_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_03_140312_drop_colums_products_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_03_140715_update_colums_products_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_05_093149_update2_colums_products.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_05_094840_create_categories_table.php
- dinh_ngoc_do/laravel-app/database/migrations/2021_09_05_101052_update3_products_table.php
- dinh_ngoc_do/laravel-app/database/seeders/CategoriesSeeder.php
- dinh_ngoc_do/laravel-app/database/seeders/DatabaseSeeder.php
- dinh_ngoc_do/laravel-app/database/seeders/ProductsSeeder.php
-- Products Table -- 
-- Categories Table --
> dinh_ngoc_do Add DB

- dinh_ngoc_do/laravel-app/resources/views/shopper-about.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-cart.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-checkout.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-contact.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-shop-single.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-shop.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-thankyou.blade.php
- dinh_ngoc_do/laravel-app/routes/web.php
Anh giang check hộ e với hôm qua đầu giờ e có hỏi ý thì em có quay vid lại vấn đề em gặp phải anh xem hộ e với
https://drive.google.com/file/d/1LqwJsKYC2HvCXn4Ju7G8duA7CbKUtd3j/view?usp=sharing
> Update View Shopper

- nguyen_van_giang/laravel-app/.gitignore
- nguyen_van_giang/laravel-app/README.md
- nguyen_van_giang/laravel-app/app/Http/Controllers/HomeController.php
- nguyen_van_giang/laravel-app/app/Http/Controllers/ProductController.php
- nguyen_van_giang/laravel-app/config/product.php
- nguyen_van_giang/laravel-app/resources/views/home-page.blade.php
- nguyen_van_giang/laravel-app/resources/views/products/show.blade.php
- nguyen_van_giang/laravel-app/routes/web.php
> [GiangNv] Query builder

- NguyenThuPhuong/phuong-app/app/Http/Controllers/HomeController.php
- NguyenThuPhuong/phuong-app/app/Providers/AppServiceProvider.php
- NguyenThuPhuong/phuong-app/config/product.php
- NguyenThuPhuong/phuong-app/database/seeders/ProductsSeeder.php
- NguyenThuPhuong/phuong-app/resources/views/home-page.blade.php
- NguyenThuPhuong/phuong-app/resources/views/layouts/myshop/my-shop.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/about-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/blog-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/blog-single-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/cart-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/checkout-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/contact-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/product-single-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/shop-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/my-directory/wishlist-ms.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/bootstrap-4.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/default.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/my-paginate.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/semantic-ui.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/simple-bootstrap-4.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/simple-default.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/simple-tailwind.blade.php
- NguyenThuPhuong/phuong-app/resources/views/pagination/tailwind.blade.php
- NguyenThuPhuong/phuong-app/routes/web.php
> [NTPhuong] Query Bilder - Show data theme

- nguyen_van_giang/laravel-app/app/Http/Controllers/HomeController.php
- nguyen_van_giang/laravel-app/app/Providers/AppServiceProvider.php
- nguyen_van_giang/laravel-app/config/product.php
- nguyen_van_giang/laravel-app/resources/views/home-page.blade.php
- nguyen_van_giang/laravel-app/resources/views/partials/my-paginate.blade.php
> [GiangNv] Custom pagination

- Manh_Tien/test1-app/app/Http/Controllers/CategoryController.php
- Manh_Tien/test1-app/app/Http/Controllers/ProductController.php
- Manh_Tien/test1-app/app/Models/Category.php
- Manh_Tien/test1-app/app/Models/ShopProduct.php
- Manh_Tien/test1-app/config/category.php
- Manh_Tien/test1-app/config/product.php
- Manh_Tien/test1-app/database/factories/CategoryFactory.php
- Manh_Tien/test1-app/database/migrations/2021_09_04_111312_create_products_table.php
- Manh_Tien/test1-app/database/migrations/2021_09_05_160429_create_shop_products_table.php
- Manh_Tien/test1-app/database/migrations/2021_09_11_184818_create_categories_table.php
- Manh_Tien/test1-app/database/seeders/CategorySeeder.php
- Manh_Tien/test1-app/resources/views/my-theme-page/categories-page.blade.php
- Manh_Tien/test1-app/resources/views/theme-home-page.blade.php
- Manh_Tien/test1-app/routes/web.php
https://user-images.githubusercontent.com/89443410/132977738-9ce68e5a-238e-4df2-8f57-06a02e6fdafd.mp4
> [TienBM] Laravel Eloquent

- tran_kien_giang/laravel_eloquent/Controller/CategoryController.php
- tran_kien_giang/laravel_eloquent/Controller/Controller.php
- tran_kien_giang/laravel_eloquent/Controller/HomeController.php
- tran_kien_giang/laravel_eloquent/Models/Category.php
- tran_kien_giang/laravel_eloquent/Models/Product.php
- tran_kien_giang/laravel_eloquent/config/category.php
- tran_kien_giang/laravel_eloquent/config/product.php
- tran_kien_giang/laravel_eloquent/routes/web.php
- tran_kien_giang/laravel_eloquent/shop-spad.blade.php
Uploading Male-Fashion _ Template - Google Chrome 2021-09-13 16-08-35.mp4…
Hello Word !!
> [Giang-TK] Laravel_elequent

- dinh_ngoc_do/laravel-app/README.md
- dinh_ngoc_do/laravel-app/app/Http/Controllers/ProductController.php
- dinh_ngoc_do/laravel-app/app/Http/Controllers/ShopController.php
- dinh_ngoc_do/laravel-app/app/Models/Category.php
- dinh_ngoc_do/laravel-app/app/Models/Product.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-shop-single.blade.php
- dinh_ngoc_do/laravel-app/resources/views/shopper-shop.blade.php
- dinh_ngoc_do/laravel-app/routes/web.php
> dinh_ngoc_do_eloquent_orm

- nguyen_van_giang/laravel-app/app/Http/Controllers/CategoryController.php
- nguyen_van_giang/laravel-app/app/Http/Controllers/ProductController.php
- nguyen_van_giang/laravel-app/app/Models/Order.php
- nguyen_van_giang/laravel-app/app/Models/Product.php
- nguyen_van_giang/laravel-app/app/Models/ProductOrder.php
- nguyen_van_giang/laravel-app/app/Models/Profile.php
- nguyen_van_giang/laravel-app/app/Models/User.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_13_122006_create_profiles_table.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_13_143613_create_orders_table.php
- nguyen_van_giang/laravel-app/database/migrations/2021_09_13_143636_create_product_orders_table.php
- nguyen_van_giang/laravel-app/database/seeders/DatabaseSeeder.php
- nguyen_van_giang/laravel-app/database/seeders/OrderSeeder.php
- nguyen_van_giang/laravel-app/database/seeders/ProductOrderSeeder.php
- nguyen_van_giang/laravel-app/database/seeders/ProfileSeeder.php
```
users  1 - 1  profile: phone, address, age, sex...
HasOne - BelongsTo
category (id)  1 -> N  products (abc_id)
category  hasMany products
1 product belongsTo category
N - N => (1 -> N, N <- 1)
users
id - integer
name - string
roles
id - integer
name - string
role_user
user_id - integer
role_id - integer
users
id      name
1       Hieu (A)
2       Giang (C)
roles
id      name
1       create product
2       view product
3       edit product
4       delete product
5       report product
role_user
user_id role_id
1       1
1       3
1       4
2       1
2       2
2       3
2       4
2       5
--------------------------------------
user A 1 - N create product, edit product, delete product 
user B 1 - N view product, report product
user C 1 - N create product, edit product, delete product, …
```
> [GiangNV] Relationship

- NguyenThuPhuong/phuong-app/app/Http/Controllers/CategoryController.php
- NguyenThuPhuong/phuong-app/app/Models/Order.php
- NguyenThuPhuong/phuong-app/app/Models/Product.php
- NguyenThuPhuong/phuong-app/app/Models/ProductOrder.php
- NguyenThuPhuong/phuong-app/app/Models/Profile.php
- NguyenThuPhuong/phuong-app/app/Models/User.php
- NguyenThuPhuong/phuong-app/database/migrations/2021_09_16_095312_create_profiles_table.php
- NguyenThuPhuong/phuong-app/database/migrations/2021_09_16_123157_update_profiles.php
- NguyenThuPhuong/phuong-app/database/migrations/2021_09_16_161017_create_orders_table.php
- NguyenThuPhuong/phuong-app/database/migrations/2021_09_16_163819_create_product_orders_table.php
- NguyenThuPhuong/phuong-app/database/seeders/DatabaseSeeder.php
- NguyenThuPhuong/phuong-app/database/seeders/OrderSeeder.php
- NguyenThuPhuong/phuong-app/database/seeders/ProductOrderSeeder.php
- NguyenThuPhuong/phuong-app/database/seeders/ProductsSeeder.php
- NguyenThuPhuong/phuong-app/database/seeders/ProfileSeeder.php
Relationships
---------------------------------------------------------------------------------
1-1 : hasOne - belongsTo
1-N: hasMany - belongsTo
N-N: belongsToMany - belongsToMany (1-N + N-1)
> [NTPhuong] - Eloquent Relationship

- cao_van_thao/laravel_app/example-app/app/Models/Order.php
- cao_van_thao/laravel_app/example-app/app/Models/OrdersProduct.php
- cao_van_thao/laravel_app/example-app/app/Models/Product.php
- cao_van_thao/laravel_app/example-app/database/migrations/2021_09_16_163646_create_orders_table.php
- cao_van_thao/laravel_app/example-app/database/migrations/2021_09_16_163723_create_orders_product_table.php
- cao_van_thao/laravel_app/example-app/database/seeders/DatabaseSeeder.php
- cao_van_thao/laravel_app/example-app/database/seeders/OrderSeeder.php
- cao_van_thao/laravel_app/example-app/database/seeders/OrdersProductSeeder.php
> Relationship

- nguyen_van_giang/laravel-app/.gitignore
- nguyen_van_giang/laravel-app/README.md
- nguyen_van_giang/laravel-app/app/Http/Controllers/Admin/ProductController.php
- nguyen_van_giang/laravel-app/app/Http/Controllers/PhotoController.php
- nguyen_van_giang/laravel-app/app/Http/Kernel.php
- nguyen_van_giang/laravel-app/app/Http/Middleware/Admin.php
- nguyen_van_giang/laravel-app/app/View/Components/AdminLayout.php
- nguyen_van_giang/laravel-app/composer.json
- nguyen_van_giang/laravel-app/composer.lock
- nguyen_van_giang/laravel-app/database/seeders/ProductSeeder.php
- nguyen_van_giang/laravel-app/public/mix-manifest.json
- nguyen_van_giang/laravel-app/resources/views/admin/products/index.blade.php
- nguyen_van_giang/laravel-app/resources/views/admin/products/show.blade.php
- nguyen_van_giang/laravel-app/resources/views/layouts/admin.blade.php
- nguyen_van_giang/laravel-app/resources/views/partials/admin-paginate.blade.php
- nguyen_van_giang/laravel-app/routes/web.php
- nguyen_van_giang/laravel-app/webpack.mix.js
http://localhost:2104/admin/products
> [GiangNV] Controller, admin layout

- tran_kien_giang/laravel_admin/Controller/Admin/ProductController.php
- tran_kien_giang/laravel_admin/Middleware/Admin.php
- tran_kien_giang/laravel_admin/components/admin.blade.php
- tran_kien_giang/laravel_admin/routes/web.php
- tran_kien_giang/laravel_admin/views/admin/products/index.blade.php
- tran_kien_giang/laravel_admin/views/admin/products/show.blade.php
- tran_kien_giang/laravel_admin/webpack.mix.js
- tran_kien_giang/laravel_relationship/Models/Category.php
- tran_kien_giang/laravel_relationship/Models/Order.php
- tran_kien_giang/laravel_relationship/Models/Product.php
- tran_kien_giang/laravel_relationship/Models/Profile.php
- tran_kien_giang/laravel_relationship/Models/User.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_13_122034_create_profiles_table.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_13_143703_create_orders_table.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_17_085638_create_product_order_table.php
- tran_kien_giang/laravel_relationship/seeder/DatabaseSeeder.php
- tran_kien_giang/laravel_relationship/seeder/OrderProductSeeder.php
- tran_kien_giang/laravel_relationship/seeder/OrderSeeder.php
- tran_kien_giang/laravel_relationship/seeder/ProfileSeeder.php
> [Giang-TK] -Laravel admin

- tran_kien_giang/laravel_relationship/Models/Category.php
- tran_kien_giang/laravel_relationship/Models/Order.php
- tran_kien_giang/laravel_relationship/Models/Product.php
- tran_kien_giang/laravel_relationship/Models/Profile.php
- tran_kien_giang/laravel_relationship/Models/User.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_13_122034_create_profiles_table.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_13_143703_create_orders_table.php
- tran_kien_giang/laravel_relationship/migrations/2021_09_17_085638_create_product_order_table.php
- tran_kien_giang/laravel_relationship/seeder/DatabaseSeeder.php
- tran_kien_giang/laravel_relationship/seeder/OrderProductSeeder.php
- tran_kien_giang/laravel_relationship/seeder/OrderSeeder.php
- tran_kien_giang/laravel_relationship/seeder/ProfileSeeder.php
> [Giang-TK] laravel_relationship

- dinh_ngoc_do/laravel-app/app/Http/Controllers/Admin/AdminProductController.php
- dinh_ngoc_do/laravel-app/app/Http/Kernel.php
- dinh_ngoc_do/laravel-app/app/Http/Middleware/Admin.php
- dinh_ngoc_do/laravel-app/resources/views/admin/admin-paginate.blade.php
- dinh_ngoc_do/laravel-app/resources/views/admin/admin-product.blade.php
- dinh_ngoc_do/laravel-app/resources/views/layouts/admin/admin-layout.blade.php
- dinh_ngoc_do/laravel-app/routes/web.php
https://drive.google.com/file/d/1Hx53rgfGr8_5CXq85G52eZP90R5GFhjb/view?usp=sharing
anh check hộ e với e k biết để video hẳn trên git ntn
> product_delete

- NguyenThuPhuong/phuong-app/app/Http/Controllers/Admin/ProductController.php
- NguyenThuPhuong/phuong-app/app/Http/Kernel.php
- NguyenThuPhuong/phuong-app/app/Http/Middleware/Admin.php
- NguyenThuPhuong/phuong-app/app/Models/Product.php
- NguyenThuPhuong/phuong-app/database/seeders/ProductsSeeder.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/create.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/edit.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/index.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/show.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/viewsAd/admin.blade.php
- NguyenThuPhuong/phuong-app/resources/views/partials/form-delete.blade.php
- NguyenThuPhuong/phuong-app/routes/web.php
https://user-images.githubusercontent.com/77055859/134816234-fe886ae8-389d-4d23-a08b-1a5928ae43e0.mp4
> [NTPhuong] CRUD: add, edit, delete product

- tran_kien_giang/Laravel_Create_Update_Delete/Controllers/Admin/ProductController.php
- tran_kien_giang/Laravel_Create_Update_Delete/Models/Product.php
- tran_kien_giang/Laravel_Create_Update_Delete/includes-admin/addedit.blade.php
- tran_kien_giang/Laravel_Create_Update_Delete/includes-admin/delete.blade.php
- tran_kien_giang/Laravel_Create_Update_Delete/views/admin/products/create.blade.php
- tran_kien_giang/Laravel_Create_Update_Delete/views/admin/products/edit.blade.php
- tran_kien_giang/Laravel_Create_Update_Delete/views/admin/products/index.blade.php
- tran_kien_giang/Laravel_Create_Update_Delete/views/admin/products/show.blade.php
buổi trc em phải làm báo cáo bài tập lớn buổi này em gửi luôn phần buổi trước ạ !!!
> [Giang-TK]_Laravel_Update_Delete_Create

- cao_van_thao/laravel_app/example-app/app/Http/Controllers/Admin/ProductController.php
- cao_van_thao/laravel_app/example-app/app/Http/Controllers/CategoryController.php
- cao_van_thao/laravel_app/example-app/config/product.php
- cao_van_thao/laravel_app/example-app/resources/views/admin/products/create.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/admin/products/index.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/layouts/admin.blade.php
- cao_van_thao/laravel_app/example-app/routes/web.php
> [thaocv]_controller_products_delete

- NguyenThuPhuong/phuong-app/app/Http/Controllers/Admin/ProductController.php
- NguyenThuPhuong/phuong-app/app/Http/Middleware/Admin.php
- NguyenThuPhuong/phuong-app/app/Http/Requests/StoreProductsRequest.php
- NguyenThuPhuong/phuong-app/app/Models/Product.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/create.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/edit.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/index.blade.php
- NguyenThuPhuong/phuong-app/resources/views/admin/products/show.blade.php
https://user-images.githubusercontent.com/77055859/135295103-990aaf3d-6b22-49e5-a6e0-ca16506208c6.mp4
> [NTPhuong] CRUD: search, upload-file & Request

- nguyen_van_giang/laravel-app/README.md
- nguyen_van_giang/laravel-app/app/Http/Controllers/Admin/ProductController.php
- nguyen_van_giang/laravel-app/app/Models/Product.php
- nguyen_van_giang/laravel-app/resources/views/admin/products/show.blade.php
- nguyen_van_giang/laravel-app/resources/views/partials/form-product.blade.php
Run command:
```
php artisan storage:link
```
https://user-images.githubusercontent.com/3873359/134793900-de308b5f-98d6-4b89-bee8-984e49ca7222.mov
> Upload file

- Le_duong/Laravel/eCommerce/.gitignore
- Le_duong/Laravel/eCommerce/app/Http/Controllers/Cart/CartController.php
- Le_duong/Laravel/eCommerce/app/Http/Controllers/Controller.php
- Le_duong/Laravel/eCommerce/app/Http/Controllers/YourCart/YourCartController.php
- Le_duong/Laravel/eCommerce/public/assets/js/main.js
- Le_duong/Laravel/eCommerce/resources/assets/js/main.js
- Le_duong/Laravel/eCommerce/resources/views/components/cart.blade.php
- Le_duong/Laravel/eCommerce/resources/views/components/modal-product.blade.php
- Le_duong/Laravel/eCommerce/resources/views/layouts/board.blade.php
- Le_duong/Laravel/eCommerce/resources/views/pages/shoping_cart.blade.php
- Le_duong/Laravel/eCommerce/resources/views/pages/shops_details.blade.php
+)Add to cart
+)Update cart
+)Delete cart
https://user-images.githubusercontent.com/80597229/136215182-c00f1f06-d6c0-44b1-9ee0-8948e19fd9db.mp4
> [Leduong]:cart

- dinh_ngoc_do/laravel-app/app/Http/Controllers/Admin/AdminProductController.php
- dinh_ngoc_do/laravel-app/app/Http/Controllers/ShopController.php
- dinh_ngoc_do/laravel-app/app/Http/Requests/StoreProductRequest.php
- dinh_ngoc_do/laravel-app/app/Models/Product.php
- dinh_ngoc_do/laravel-app/app/Models/User.php
- dinh_ngoc_do/laravel-app/app/Rules/ProductName.php
- dinh_ngoc_do/laravel-app/app/View/Components/ImageLink.php
- dinh_ngoc_do/laravel-app/resources/views/admin/partials/admin-form-product.blade.php
- dinh_ngoc_do/laravel-app/resources/views/admin/product/admin-product.blade.php
- dinh_ngoc_do/laravel-app/resources/views/admin/product/admin-products-history.blade.php
anh merged pull này bỏ cái pull cũ (https://github.com/VanGiang/php2104_php/pull/163) hộ e nhé
> add_validation

- cao_van_thao/laravel_app/example-app/app/Http/Controllers/Admin/ProductController.php
- cao_van_thao/laravel_app/example-app/app/Http/Requests/StoreProductRequest.php
- cao_van_thao/laravel_app/example-app/app/Rules/Valirequetsname.php
- cao_van_thao/laravel_app/example-app/resources/views/home-page.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/layouts/customers/my-app.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/partials/admin/from-product.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/partials/header.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/partials/menu-top.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/products/product-detail.blade.php
- cao_van_thao/laravel_app/example-app/resources/views/products/product.blade.php
> [thaocv]rule_Valiname
